---
title: "Final report"
author: "Peng Liu, Mi Zhang"
date: "4/25/2022"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(kableExtra)

library(tidyverse)
library(R.matlab)
library(e1071)
library(caret)
#install.packages("facetoextra")
library(factoextra)
library(ggbiplot)
library(psych)
library(devtools)
library(pROC)
```

```{r}
Mice<- c("409", "412", "414", "416", "417", "418")

Total_neurons<- c("110", "100", "33", "26", "79", "77")

Accuracy<- c("0.8955", "0.9403", "0.7373", "0.7271", "0.9476", "0.9168")

AUC_score <- c("0.9582", "0.9623", "0.7870", "0.7852", "0.9684", "0.9505")

kable(cbind(Mice, Total_neurons, Accuracy, AUC_score),"pipe", caption = "Comparison of GLMs for Six Mouse")
```



```{r warning=FALSE}
Mice<- c("409", "412", "414", "416", "417", "418")

KMO <- c("93", "77", "80", "61", "73", "78")

PC_number <- c("24", "27", "11", "11", "24", "24")

Accuracy <- c("0.8109", "0.8385", "0.6587", "0.7033", "0.9012", "0.8573")

AUC_score <- c("0.8710", "0.8520", "0.7069", "0.7365", "0.9015", "0.8737")

kable(cbind(Mice, KMO, PC_number, Accuracy, AUC_score),"pipe", caption = "Comparison of GLM after PCA") %>% kable_styling(bootstrap_options = c("striped", "hover"))

```